services:
  onlycats-postservice:
    build:
      context: .
      dockerfile: Onlycats.PostService/Dockerfile
    ports:
      - "8080:80"
    networks:
      - onlycats-network
    secrets: 
      - mongodb_connection_string
    volumes:
      - ./Onlycats.PostService:/src/Onlycats.PostService
  onlycats-interactionservice:
     build:
       context: .
       dockerfile: Onlycats.InteractionService/Dockerfile
     ports:
       - "8081:81"
     networks:
       - onlycats-network
     environment:
       - ASPNETCORE_ENVIRONMENT=Development
     secrets: 
       - mongodb_connection_string
     volumes:
      - ./Onlycats.InteractionService:/src/Onlycats.InteractionService

  onlycats-userservice:
     build:
       context: .
       dockerfile: Onlycats.UserService/Dockerfile
     ports:
       - "8082:82"
     networks:
       - onlycats-network
     environment:
       - ASPNETCORE_ENVIRONMENT=Development
     secrets:
       - postgres_connection_string
     volumes:
       - ./Onlycats.UserService:/src/Onlycats.UserService
  onlycats:
     build:
       context: ./Onlycats/Onlycats
       dockerfile: Dockerfile
     ports:
       - "8000:8000"
     networks:
       - onlycats-network
     environment:
       - ASPNETCORE_ENVIRONMENT=Development
     volumes:
       - ./Onlycats:/src/Onlycats
     depends_on:
       - onlycats-postservice
       - onlycats-interactionservice
       - onlycats-userservice
networks:
  onlycats-network:
    driver: bridge
secrets:
  mongodb_connection_string:
    external: true
  postgres_connection_string:
    external: true