services:
  postservice:
    build:
      context: .
      dockerfile: Onlycats.PostService/Dockerfile
    ports:
      - "8083:8080"
    networks:
      - onlycats-network
    # secrets: 
    #   - mongodb_connection_string
    volumes:
      - ./Onlycats.PostService:/src/Onlycats.PostService
  interactionservice:
     build:
       context: .
       dockerfile: Onlycats.InteractionService/Dockerfile
     ports:
       - "8081:8080"
     networks:
       - onlycats-network
     environment:
       - ASPNETCORE_ENVIRONMENT=Development
    #  secrets: 
    #    - mongodb_connection_string
     volumes:
      - ./Onlycats.InteractionService:/src/Onlycats.InteractionService
    
  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: onlycats
    ports:
      - "5432:5432"
    networks:
      - onlycats-network
    volumes:
      - pgdata:/var/lib/postgresql/data
  userservice:
     build:
       context: .
       dockerfile: Onlycats.UserService/Dockerfile
     ports:
       - "8082:8080"
     networks:
       - onlycats-network
     environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - POSTGRES_HOST=onlycats-postgresdb-1
       - POSTGRES_PORT=5432
       - POSTGRES_DB=onlycats
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=1234
     depends_on:
       - postgresdb
     command: >
       sh -c "dotnet ef migrations add InitialCreate; dotnet ef database update --no-build; dotnet Onlycats.UserService.dll"
    #  secrets:
    #    - postgres_connection_string
     volumes:
       - ./Onlycats.UserService:/src/Onlycats.UserService
  gateway:
     build:
       context: ./Gateway
       dockerfile: Dockerfile
     ports:
       - "8000:8080"
     networks:
       - onlycats-network
     environment:
       - ASPNETCORE_ENVIRONMENT=Development
     volumes:
       - ./Onlycats:/src/Onlycats
     depends_on:
       - postservice
       - interactionservice
       - userservice
networks:
  onlycats-network:
    driver: bridge
    attachable: true
volumes:
 pgdata:
# secrets:
#   mongodb_connection_string:
#     external: true
#   postgres_connection_string:
#     external: true