services:
  postservice:
    build:
      context: .
      dockerfile: Onlycats.PostService/Dockerfile
    ports:
      - "8083:8080"
    networks:
      - onlycats-network
    # secrets: 
    #   - mongodb_connection_string
    volumes:
      - ./Onlycats.PostService:/src/Onlycats.PostService
  interactionservice:
     build:
       context: .
       dockerfile: Onlycats.InteractionService/Dockerfile
     ports:
       - "8081:8080"
     networks:
       - onlycats-network
     environment:
       - ASPNETCORE_ENVIRONMENT=Development
    #  secrets: 
    #    - mongodb_connection_string
     volumes:
      - ./Onlycats.InteractionService:/src/Onlycats.InteractionService
  userservice:
     build:
       context: .
       dockerfile: Onlycats.UserService/Dockerfile
     ports:
       - "8082:8080"
     networks:
       - onlycats-network
     environment:
       - ASPNETCORE_ENVIRONMENT=Development
    #  secrets:
    #    - postgres_connection_string
     volumes:
       - ./Onlycats.UserService:/src/Onlycats.UserService
  gateway:
     build:
       context: ./Gateway
       dockerfile: Dockerfile
     ports:
       - "8000:8080"
     networks:
       - onlycats-network
     environment:
       - ASPNETCORE_ENVIRONMENT=Development
     volumes:
       - ./Onlycats:/src/Onlycats
     depends_on:
       - postservice
       - interactionservice
       - userservice
networks:
  onlycats-network:
    driver: bridge
    attachable: true
# secrets:
#   mongodb_connection_string:
#     external: true
#   postgres_connection_string:
#     external: true